Feature/button component
isdi-coders-2023/coding-adventure-Ana-Coronel-front-202301-BCN pull request #1
Opened 2023-02-27 15:23 UTC by a9nna

Create a Button component, test it and add styles

2023-02-27 15:59 UTC, bertoforteza commented on src/components/Button/ButtonStyled.tsx
> +  }
Veo que has gestionado la media query para desktop, pero fíjate que en figma el button tiene también el estado `disabled`, no es que en desktop tenga una opacidad diferente. Añade esa funcionalidad al button

2023-02-27 16:04 UTC, a9nna commented on src/components/Button/ButtonStyled.tsx
> +  }
Voy!

2023-02-27 16:27 UTC, bertoforteza submitted a review, later dismissed

2023-02-27 16:27 UTC, bertoforteza commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Podrías pasar los colores a variables? Sino podrías probar de usar un `ThemeProvider`

2023-02-27 16:28 UTC, a9nna commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Ahora me pongo

2023-02-27 16:47 UTC, a9nna commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Done!

2023-02-27 20:50 UTC, a9nna commented
Ya está el Theme Provider reubicado

2023-02-28 11:14 UTC, a9nna commented
@benjaminrae

2023-02-28 11:26 UTC, MMLORENA submitted a review, later dismissed

2023-02-28 11:26 UTC, MMLORENA commented on src/styles/GlobalStyle.tsx
> +  font-family: "Saira Stencil One";
Debería estar en el theme provider las fuentes y para eso fijate que no el GlobalStyle está mal instanciado en Index

2023-02-28 11:26 UTC, MMLORENA commented on src/styles/theme.tsx
> +const theme = {
Te recomiendo revisar el tipado del ThemeProvider

2023-02-28 12:21 UTC, a9nna commented on src/styles/theme.tsx
> +const theme = {
Tipado implementado

2023-02-28 12:23 UTC, benjaminrae requested changes

2023-02-28 12:23 UTC, benjaminrae commented on src/components/Button/Button.tsx
> +    <>
Necesitamos este fragmento?

2023-02-28 12:23 UTC, benjaminrae commented
@a9nna tienes conflictos para resolver

2023-02-28 12:27 UTC, a9nna commented on src/components/Button/Button.tsx
> +    <>
Cierto, no haría falta, ya está eliminado

2023-02-28 12:31 UTC, benjaminrae approved these changes
@a9nna sigue con esto: Dale estilos al formulario (no dar estilo al input type file).

2023-02-28 12:33 UTC, merged