Create RegisterForm component
isdi-coders-2023/coding-adventure-Ana-Coronel-front-202301-BCN pull request #2
Opened 2023-02-27 15:48 UTC by a9nna

Create RegisterForm

2023-02-27 16:06 UTC, MMLORENA requested changes

2023-02-27 16:06 UTC, MMLORENA commented on src/components/RegisterForm/RegisterForm.tsx
> +      <h3>Register for the event</h3>
¿Por qué es un h3?

2023-02-27 16:06 UTC, MMLORENA commented on src/components/RegisterForm/RegisterForm.tsx
> +          <input type="text" placeholder="Introduce your password" />
No es type text el input

2023-02-27 16:27 UTC, a9nna commented on src/components/RegisterForm/RegisterForm.tsx
> +          <input type="text" placeholder="Introduce your password" />
Cierto, lo arreglo!

2023-02-27 16:28 UTC, a9nna commented on src/components/RegisterForm/RegisterForm.tsx
> +      <h3>Register for the event</h3>
Pensaba que seria adecuado ponerlo de esta manera, pero revisando veo que no tiene sentido, lo arreglo

2023-02-27 16:31 UTC, MMLORENA commented on src/components/RegisterForm/RegisterForm.tsx
> +          <input type="text" placeholder="Introduce your password" />
okey

2023-02-27 16:34 UTC, MMLORENA requested changes
Los campos del form son los del figma; email, password e input. Y existe un input type email

2023-02-27 16:55 UTC, a9nna commented
Cambiado!

2023-02-27 17:04 UTC, MMLORENA commented
Ya tienes test, deberías quitar del script de test el PassWithNoTest

2023-02-27 17:04 UTC, MMLORENA requested changes

2023-02-27 17:04 UTC, MMLORENA commented on src/components/RegisterForm/RegisterForm.tsx
> +      <span>Register for the event</span>
¿Por qué un span?

2023-02-27 20:53 UTC, a9nna commented on src/components/RegisterForm/RegisterForm.tsx
> +      <span>Register for the event</span>
Por que considero que es lo más indicado para poner un título al formulario

2023-02-27 21:52 UTC, a9nna commented
Habia eliminado el PassWithNoTest pero como en esta rama no hay tests el workflow de tests no pasaba

2023-02-28 11:14 UTC, a9nna commented
@MMLORENA

2023-02-28 11:27 UTC, MMLORENA commented on src/components/RegisterForm/RegisterForm.tsx
> +      <span>Register for the event</span>
Tu misma estas diciendo que es un título, no debería ser un heading?¿

2023-02-28 11:29 UTC, MMLORENA approved these changes

2023-02-28 12:21 UTC, merged